# Generated by Django 4.2 on 2023-05-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_cmts',
            field=models.IntegerField(default=0),
        ),
    ]
