# Generated by Django 4.2 on 2023-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
