# Generated by Django 4.2 on 2023-05-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_forget_password_token'),
        ('core', '0007_profile_lastlogin'),
    ]

    operations = [
    ]
